name: ci

on:
  push:
  
jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      #- name: Go env
      #uses: actions/setup-go@v2
      #with:
      #go-version: 1.15.x
      - uses: actions/checkout@v2
      - name: Build The Docker Image
        run: |
          docker build --tag st .
